### ISSUE TITLE
community/user/base.mako が見つからずビルドできない

### ISSUE THREAD

**Issue by hideyukisaito** [tado/ofSiteJp#29]
新規にローカル環境を構築しようとしているのですが、以下のエラーで `blogfile build` が通りません。
おそらく `community/user/base.mako` が無いためだと思うのですが、対策ご存知でしょうか？

```shell
ERROR:blogofile.template:Error rendering template: community/user/index.html.mako


Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Blogofile-0.8.3-py2.7.egg/blogofile/template.py", line 154, in render
    rendered = self.mako_template.render(**self)
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/runtime.py", line 863, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/runtime.py", line 805, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "community/user/index.html.mako", line 1, in _mako_inherit
    #coding:utf-8
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/runtime.py", line 762, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/runtime.py", line 795, in _lookup_template
    raise exceptions.TemplateLookupException(str(compat.exception_as()))
TemplateLookupException: Cant locate template for uri u'community/user/base.mako'

ERROR:blogofile:Fatal build error occured, calling bf.config.build_exception()
Traceback (most recent call last):
  File "/usr/local/bin/blogofile", line 9, in <module>
    load_entry_point('Blogofile==0.8.3', 'console_scripts', 'blogofile')()
  File "/Library/Python/2.7/site-packages/Blogofile-0.8.3-py2.7.egg/blogofile/main.py", line 58, in main
    args.func(args)
  File "/Library/Python/2.7/site-packages/Blogofile-0.8.3-py2.7.egg/blogofile/main.py", line 388, in do_build
    writer.write_site()
  File "/Library/Python/2.7/site-packages/Blogofile-0.8.3-py2.7.egg/blogofile/writer.py", line 50, in write_site
    self.__write_files()
  File "/Library/Python/2.7/site-packages/Blogofile-0.8.3-py2.7.egg/blogofile/writer.py", line 127, in __write_files
    util.path_join(root, html_path))
  File "/Library/Python/2.7/site-packages/Blogofile-0.8.3-py2.7.egg/blogofile/template.py", line 386, in materialize_template
    template.render(location)
  File "/Library/Python/2.7/site-packages/Blogofile-0.8.3-py2.7.egg/blogofile/template.py", line 154, in render
    rendered = self.mako_template.render(**self)
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/runtime.py", line 863, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/runtime.py", line 805, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "community_user_index_html_mako", line 25, in _mako_inherit
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/runtime.py", line 762, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "/Library/Python/2.7/site-packages/Mako-1.0.3-py2.7.egg/mako/runtime.py", line 795, in _lookup_template
    raise exceptions.TemplateLookupException(str(compat.exception_as()))
mako.exceptions.TemplateLookupException: Cant locate template for uri u'community/user/base.mako'
```

**Comment by tado** [comment]
今確認してみたところ、こちらのリポジトリ内にも
community/user/base.mako 
は存在しないので、原因は別のところにありそうです。(blogofileいろいろ謎が多いのですよね…) 調査してみますので、少し時間ください。

ちなみに、Blogofileとpythonのバージョンはいくつか教えていただけないでしょうか。

**Comment by hideyukisaito** [comment]
おっと、そうでしたか。。とりあえずは翻訳に専念することにします。

バージョンは
- Blogfile 0.8.3
- Python 2.7

です。
